[package]
name = "apex-core"
version.workspace = true
edition.workspace = true

[dependencies]
common.path = "../common"
types.path = "../types"
config.path = "../config"
metrics.path = "../metrics"
solana-sdk.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
indexmap.workspace = true
ahash.workspace = true
smallvec.workspace = true
rust_decimal.workspace = true
dashmap.workspace = true
parking_lot.workspace = true
crossbeam.workspace = true
crossbeam-channel.workspace = true

[dev-dependencies]
proptest.workspace = true
arbitrary.workspace = true
