[package]
name = "jito-integration"
version.workspace = true
edition.workspace = true

[dependencies]
common.path = "../common"
types.path = "../types"
config.path = "../config"
metrics.path = "../metrics"
solana-sdk.workspace = true
solana-client.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
bs58.workspace = true
bincode.workspace = true
borsh.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
